switch continue-on-error away

diff --git a/.github/workflows/2025-07-31.yaml b/.github/workflows/2025-07-31.yaml
--- a/.github/workflows/2025-07-31.yaml
+++ b/.github/workflows/2025-07-31.yaml
@@ -12,9 +12,9 @@ jobs:
         uses: actions/checkout@v4
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - run: echo "Throwing an error, but next step should still run!" && exit 1
-      - name: List files in the repository
-        continue-on-error: true
+      - continue-on-error: true
+        run: echo "Throwing an error, but next step should still run!" && exit 1
+      - name: List files in the repository        
         run: |
           ls ${{ github.workspace }}
       - run: echo "🍏 This job's status is ${{ job.status }}."
